// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace BackEnd.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Models.Staniste", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Boja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Boja");

                    b.Property<int>("Max")
                        .HasColumnType("int")
                        .HasColumnName("Max");

                    b.Property<int>("Trenutno")
                        .HasColumnType("int")
                        .HasColumnName("Trenutno");

                    b.Property<string>("Vrsta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vrsta");

                    b.Property<int>("ZooVrtID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ZooVrtID");

                    b.ToTable("Stanište");
                });

            modelBuilder.Entity("Models.ZooVrt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("BojeStanista")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Boje Stanista");

                    b.Property<int>("M")
                        .HasColumnType("int")
                        .HasColumnName("M");

                    b.Property<int>("Max")
                        .HasColumnType("int")
                        .HasColumnName("Max");

                    b.Property<int>("N")
                        .HasColumnType("int")
                        .HasColumnName("N");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naziv");

                    b.Property<string>("TipoviStanista")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tipovi Stanista");

                    b.HasKey("ID");

                    b.ToTable("Zoo Vrt");
                });

            modelBuilder.Entity("Models.Staniste", b =>
                {
                    b.HasOne("Models.ZooVrt", null)
                        .WithMany("Stanista")
                        .HasForeignKey("ZooVrtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.ZooVrt", b =>
                {
                    b.Navigation("Stanista");
                });
#pragma warning restore 612, 618
        }
    }
}
