// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

namespace backend.Migrations
{
    [DbContext(typeof(EvidencijaContext))]
    partial class EvidencijaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("backend.Models.Fabrika", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Fabrika");
                });

            modelBuilder.Entity("backend.Models.Silos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int?>("FabrikaID")
                        .HasColumnType("int");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<string>("Oznaka")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Oznaka");

                    b.Property<int>("TrenutnaKolicina")
                        .HasColumnType("int")
                        .HasColumnName("Treutna Količina");

                    b.HasKey("ID");

                    b.HasIndex("FabrikaID");

                    b.ToTable("Silos");
                });

            modelBuilder.Entity("backend.Models.Silos", b =>
                {
                    b.HasOne("backend.Models.Fabrika", "Fabrika")
                        .WithMany("Silosi")
                        .HasForeignKey("FabrikaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Fabrika");
                });

            modelBuilder.Entity("backend.Models.Fabrika", b =>
                {
                    b.Navigation("Silosi");
                });
#pragma warning restore 612, 618
        }
    }
}
