// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backEnd.Models;

namespace backEnd.Migrations
{
    [DbContext(typeof(KluboviContext))]
    [Migration("20210205225218_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("backEnd.Models.Polica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("Current")
                        .HasColumnType("int")
                        .HasColumnName("Trenutni Broj DVD-ova");

                    b.Property<int>("Max")
                        .HasColumnType("int")
                        .HasColumnName("Maksimalni Broj DVD-ova");

                    b.Property<string>("Oznaka")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Oznaka");

                    b.Property<int>("VideoKlubID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VideoKlubID");

                    b.ToTable("Polica");
                });

            modelBuilder.Entity("backEnd.Models.VideoKlub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Video Klub");
                });

            modelBuilder.Entity("backEnd.Models.Polica", b =>
                {
                    b.HasOne("backEnd.Models.VideoKlub", null)
                        .WithMany("Police")
                        .HasForeignKey("VideoKlubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backEnd.Models.VideoKlub", b =>
                {
                    b.Navigation("Police");
                });
#pragma warning restore 612, 618
        }
    }
}
